version: '3'
services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./src/server:/server

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: recipe_suggester
    ports:
      - "3307:3306"
